//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DizzyProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DizzyProject.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input does not match validation criteria..
        /// </summary>
        public static string ApiError40Description {
            get {
                return ResourceManager.GetString("ApiError40Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string ApiError40Title {
            get {
                return ResourceManager.GetString("ApiError40Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string ApiError41Description {
            get {
                return ResourceManager.GetString("ApiError41Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        public static string ApiError41Title {
            get {
                return ResourceManager.GetString("ApiError41Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another user is already registered with the given email address..
        /// </summary>
        public static string ApiError42Description {
            get {
                return ResourceManager.GetString("ApiError42Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        public static string ApiError42Title {
            get {
                return ResourceManager.GetString("ApiError42Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled service error..
        /// </summary>
        public static string ApiError50Description {
            get {
                return ResourceManager.GetString("ApiError50Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Error.
        /// </summary>
        public static string ApiError50Title {
            get {
                return ResourceManager.GetString("ApiError50Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ApiErrorDefaultDescription {
            get {
                return ResourceManager.GetString("ApiErrorDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ApiErrorDefaultTitle {
            get {
                return ResourceManager.GetString("ApiErrorDefaultTitle", resourceCulture);
            }
        }
    }
}
