//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DizzyProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DizzyProject.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error..
        /// </summary>
        public static string ApiError40001validation {
            get {
                return ResourceManager.GetString("ApiError40001validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string ApiError40002invalidEmailOrPassword {
            get {
                return ResourceManager.GetString("ApiError40002invalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already registered..
        /// </summary>
        public static string ApiError40003userAlreadyRegistered {
            get {
                return ResourceManager.GetString("ApiError40003userAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. No token provided..
        /// </summary>
        public static string ApiError40004noToken {
            get {
                return ResourceManager.GetString("ApiError40004noToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string ApiError40005invalidToken {
            get {
                return ResourceManager.GetString("ApiError40005invalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url parameter must be a number..
        /// </summary>
        public static string ApiError40006urlParameterNumber {
            get {
                return ResourceManager.GetString("ApiError40006urlParameterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect..
        /// </summary>
        public static string ApiError40007currentPasswordIncorrect {
            get {
                return ResourceManager.GetString("ApiError40007currentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city/country does not exist..
        /// </summary>
        public static string ApiError40008locationNotFound {
            get {
                return ResourceManager.GetString("ApiError40008locationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation already exists..
        /// </summary>
        public static string ApiError40009relationExists {
            get {
                return ResourceManager.GetString("ApiError40009relationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dizziness register requires a level from 0-10..
        /// </summary>
        public static string ApiError40010levelRequired {
            get {
                return ResourceManager.GetString("ApiError40010levelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint can only be used by physiotherapists..
        /// </summary>
        public static string ApiError40301onlyPhysiotherapist {
            get {
                return ResourceManager.GetString("ApiError40301onlyPhysiotherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint can only be used by patients..
        /// </summary>
        public static string ApiError40302onlyPatient {
            get {
                return ResourceManager.GetString("ApiError40302onlyPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to the specified element..
        /// </summary>
        public static string ApiError40303accessDenied {
            get {
                return ResourceManager.GetString("ApiError40303accessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user no longer exists..
        /// </summary>
        public static string ApiError40401userNotFound {
            get {
                return ResourceManager.GetString("ApiError40401userNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element could not be found..
        /// </summary>
        public static string ApiError40402elementNotFound {
            get {
                return ResourceManager.GetString("ApiError40402elementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        public static string ApiError50001internalServerError {
            get {
                return ResourceManager.GetString("ApiError50001internalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to server..
        /// </summary>
        public static string ConnectionException {
            get {
                return ResourceManager.GetString("ConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Service Error.
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
    }
}
