//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DizzyProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DizzyProject.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error..
        /// </summary>
        public static string ApiError40001Validation {
            get {
                return ResourceManager.GetString("ApiError40001Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string ApiError40002InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("ApiError40002InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already registered..
        /// </summary>
        public static string ApiError40003UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("ApiError40003UserAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. No token provided..
        /// </summary>
        public static string ApiError40004NoToken {
            get {
                return ResourceManager.GetString("ApiError40004NoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string ApiError40005InvalidToken {
            get {
                return ResourceManager.GetString("ApiError40005InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url parameter must be a number..
        /// </summary>
        public static string ApiError40006UrlParameterNumber {
            get {
                return ResourceManager.GetString("ApiError40006UrlParameterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect..
        /// </summary>
        public static string ApiError40007CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("ApiError40007CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city/country does not exist..
        /// </summary>
        public static string ApiError40008LocationNotFound {
            get {
                return ResourceManager.GetString("ApiError40008LocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation already exists..
        /// </summary>
        public static string ApiError40009RelationExists {
            get {
                return ResourceManager.GetString("ApiError40009RelationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dizziness register requires a level from 0-10..
        /// </summary>
        public static string ApiError40010LevelRequired {
            get {
                return ResourceManager.GetString("ApiError40010LevelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint can only be used by physiotherapists..
        /// </summary>
        public static string ApiError40301OnlyPhysiotherapist {
            get {
                return ResourceManager.GetString("ApiError40301OnlyPhysiotherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint can only be used by patients..
        /// </summary>
        public static string ApiError40302OnlyPatient {
            get {
                return ResourceManager.GetString("ApiError40302OnlyPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to the specified element..
        /// </summary>
        public static string ApiError40303AccessDenied {
            get {
                return ResourceManager.GetString("ApiError40303AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user no longer exists..
        /// </summary>
        public static string ApiError40401UserNotFound {
            get {
                return ResourceManager.GetString("ApiError40401UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element could not be found..
        /// </summary>
        public static string ApiError40402ElementNotFound {
            get {
                return ResourceManager.GetString("ApiError40402ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        public static string ApiError50001InternalServerError {
            get {
                return ResourceManager.GetString("ApiError50001InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to server..
        /// </summary>
        public static string ConnectionException {
            get {
                return ResourceManager.GetString("ConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Service Error.
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
    }
}
